### ISSUE TITLE
LinuxでGrapheneを開くと、設定ペインが最大化されてしまう

### ISSUE THREAD

**Issue by nikosai** [lmntal/Graphene#6]
原因不明かつ長らく放置されているが、LinuxでGrapheneを起動した際に右側の設定ペインが最大化され、肝心の左側のグラフがほとんど見えない状態になってしまうバグがある。

**Comment by k-ueda** [comment]
https://github.com/lmntal/Graphene/commit/e2f48fd98e653b0b840363e7c679dcc012a800d6 によって解決しています．develop (Scala 2.10) および scala-2.11 ブランチにも反映済み．
