### ISSUE TITLE
ProGuardおよびminify.shの動作

### ISSUE THREAD

**Issue by nikosai** [lmntal/Graphene#7]
ProGuardの動作やそれを使ったminify.shの動作には疑問点が多い
- `config.pro` の1行目は環境依存なので `-libraryjars <java.home>/lib/rt.jar` のようにすべき
- `minify.sh` も以下のようにすべき
```bash
#!/bin/sh
cd `dirname $0`
target=target/scala-2.10

jar=`ls $target | grep -E 'Graphene-assembly-[0-9]+\.[0-9]+\.[0-9]+\.jar'`
minjar=`echo $jar | sed 's/Graphene-assembly-\(.*\)\.jar/graphene-\1.min.jar/g'`
java -Xms1G -Xmx4G -jar ./proguard/lib/proguard.jar -injars $target/$jar -outjars $target/$minjar @config.pro
```
- `minify.sh` にjarが見つからなかった場合の対処を追加すべき
- Java 1.7以下でないと動かないらしい
  + 同梱されているProGuard自身のバージョンが古い？
  + そもそもProGuardの同梱はライセンス上大丈夫なのか不安

**Comment by k-ueda** [comment]
ProgGuard の最新版をもってきてもうまく動かせず，しかも build.sbt の libraryDependencies の見直しで Graphene*.jar のサイズをだいぶ落とせた（現在15MB程度）ので，当面使わなくても（＋同梱を中止しても）よいと思います．
